const $=s=>document.querySelector(s), state={books:[],book:null,questions:[],queue:[],i:0,filter:'all'};
const icons={Chemistry:'⚗️',Biology:'🧬',Physics:'⚡',English:'📖',Urdu:'📝'};
const progress=id=>JSON.parse(localStorage.getItem('smart-study:'+id)||'{"correct":[],"wrong":[],"seen":[]}');
const save=(id,p)=>localStorage.setItem('smart-study:'+id,JSON.stringify(p));
const shuffle=a=>[...a].sort(()=>Math.random()-.5); const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function init(){state.books=(await (await fetch('data/books.json')).json()).books;home()}
function home(){$('#app').innerHTML=`<main class="wrap"><header class="top"><div><div class="brand">Grade 9 <span>Smart Study</span></div><div class="sub">Textbook → weak spots → targeted practice.</div></div></header><section class="panel"><h2>📚 Your Book Library</h2><p class="muted">Each subject keeps its own progress on this device.</p></section><div class="grid">${state.books.map(b=>`<article class="card" onclick="openBook('${b.id}')"><div class="emoji">${icons[b.subject]||'📚'}</div><h3>${esc(b.title)}</h3><div class="muted">${b.subject} · Grade ${b.grade}</div><div style="margin-top:12px"><span class="pill">${b.status==='starter'?'Starter pack':'Ready to import'}</span></div></article>`).join('')}</div></main>`}
async function openBook(id){state.book=state.books.find(b=>b.id===id);if(!state.book.pack){emptyBook();return}state.questions=(await (await fetch(state.book.pack)).json()).questions||[];bookHome()}
function emptyBook(){$('#app').innerHTML=`<main class="wrap"><button class="btn" onclick="home()">← Library</button><div class="panel"><h1>${icons[state.book.subject]||'📚'} ${esc(state.book.title)}</h1><p class="muted">This subject is ready for a book pack. Add its JSON pack and set the path in data/books.json.</p></div></main>`}
function filtered(){return state.filter==='all'?state.questions:state.questions.filter(q=>q.chapter===state.filter)}
function bookHome(){let p=progress(state.book.id),ch=[...new Set(state.questions.map(q=>q.chapter))].sort((a,b)=>+a-+b);$('#app').innerHTML=`<main class="wrap"><button class="btn" onclick="home()">← Library</button><header class="top"><div><div class="brand">${icons[state.book.subject]||'📚'} ${esc(state.book.title)}</div><div class="sub">${state.questions.length} loaded questions</div></div></header><div class="stats"><div class="stat"><b>${p.correct.length}</b><small>Known</small></div><div class="stat"><b>${p.wrong.length}</b><small>Wrong</small></div><div class="stat"><b>${Math.max(0,state.questions.length-p.seen.length)}</b><small>Unseen</small></div></div><div class="panel"><h3>🎯 Practice</h3><div class="toolbar"><button class="btn primary" onclick="start('smart')">Smart Practice</button><button class="btn" onclick="start('revision')">Revision Mode</button><button class="btn" onclick="start('random')">Quick Random 20</button><button class="btn" onclick="studyAll()">Study All</button></div><select onchange="state.filter=this.value"><option value="all">All chapters</option>${ch.map(x=>`<option value="${x}">Chapter ${x}</option>`).join('')}</select></div><div class="panel"><b>Smart Practice:</b> <span class="muted">unseen + anything you previously got wrong. Correct answers move into Known.</span></div></main>`}
function start(mode){let a=filtered(),p=progress(state.book.id);if(mode==='smart')a=a.filter(q=>!p.correct.includes(q.id));a=mode==='random'?shuffle(a).slice(0,20):shuffle(a);if(!a.length){alert('Nothing left in this selection 🎯');return}state.queue=a;state.i=0;renderQ()}
function renderQ(){$('#app').innerHTML=`<main class="wrap"><button class="btn" onclick="bookHome()">← ${esc(state.book.title)}</button><div class="panel"><div class="qnum">Question ${state.i+1} / ${state.queue.length} · ${esc(state.queue[state.i].topic)}</div><div class="question">${esc(state.queue[state.i].question)}</div><div class="options">${state.queue[state.i].options.map((o,n)=>`<button class="opt" onclick="answer(${n})">${String.fromCharCode(65+n)}. ${esc(o)}</button>`).join('')}</div><div id="feedback"></div></div></main>`}
function answer(n){let q=state.queue[state.i],p=progress(state.book.id),ok=n===q.correct;if(!p.seen.includes(q.id))p.seen.push(q.id);if(ok){if(!p.correct.includes(q.id))p.correct.push(q.id);p.wrong=p.wrong.filter(x=>x!==q.id)}else{if(!p.wrong.includes(q.id))p.wrong.push(q.id);p.correct=p.correct.filter(x=>x!==q.id)}save(state.book.id,p);document.querySelectorAll('.opt').forEach((b,i)=>{if(i===q.correct)b.classList.add('correct');if(i===n&&i!==q.correct)b.classList.add('wrong')});$('#feedback').innerHTML=`<div class="reason"><b>${ok?'✅ Correct':'❌ Not quite'}</b><br>${esc(q.reason)}<div class="toolbar"><button class="btn primary" onclick="nextQ()">${state.i+1===state.queue.length?'Finish':'Next →'}</button></div></div>`}
function nextQ(){state.i++;state.i>=state.queue.length?bookHome():renderQ()}
function studyAll(){state.queue=filtered();state.i=0;renderStudy()}
function renderStudy(){let q=state.queue[state.i];$('#app').innerHTML=`<main class="wrap"><button class="btn" onclick="bookHome()">← Back</button><div class="panel"><div class="qnum">Study ${state.i+1}/${state.queue.length} · ${esc(q.topic)}</div><div class="question">${esc(q.question)}</div><p><b>Answer:</b> ${esc(q.options[q.correct])}</p><div class="reason">${esc(q.reason)}</div><div class="toolbar"><button class="btn primary" onclick="state.i++;state.i>=state.queue.length?bookHome():renderStudy()">Next →</button></div></div></main>`}
init();
