let state=JSON.parse(localStorage.studyforge||'{"history":[],"seen":[]}'), current=[],idx=0,score=0;
const $=x=>document.querySelector(x); const $$=x=>[...document.querySelectorAll(x)];
function save(){localStorage.studyforge=JSON.stringify(state)}
function show(id){$$('.page').forEach(x=>x.classList.add('hidden'));$('#'+id).classList.remove('hidden');$('#title').textContent=id[0].toUpperCase()+id.slice(1); if(id==='weak')renderWeak();if(id==='progress')renderProgress()}
function stats(){let m={};state.history.forEach(x=>{m[x.topic]??={n:0,c:0};m[x.topic].n++;m[x.topic].c+=x.ok});return Object.entries(m).map(([topic,x])=>({topic,n:x.n,acc:Math.round(x.c/x.n*100)})).sort((a,b)=>a.acc-b.acc)}
function init(){ $('#bookcount').textContent=BOOKS.length;let h=state.history;$('#answered').textContent=h.length;$('#accuracy').textContent=h.length?Math.round(h.filter(x=>x.ok).length/h.length*100)+'%':'—';let s=stats();$('#weakcount').textContent=s.filter(x=>x.n>1&&x.acc<70).length;$('#priority').innerHTML=s.slice(0,6).map(x=>`<div class=row><span>${x.topic}</span><b>${x.acc}%</b></div>`).join('')||'<p style="color:#78849a">No data yet. Go get some questions wrong 😈</p>';$('#book').innerHTML=BOOKS.map(b=>`<option value="${b.id}">${b.name}</option>`).join('');chapters();renderBooks()}
function chapters(){let b=BOOKS.find(x=>x.id==$('#book').value)||BOOKS[0];$('#chapter').innerHTML='<option value="ALL">All chapters</option>'+b.chapters.map(x=>`<option>${x}</option>`).join('')}
$('#book').onchange=chapters;
function start(){let bid=$('#book').value,ch=$('#chapter').value,mode=$('#mode').value,n=+$('#n').value;let pool=Q.filter(x=>x[0]===bid&&(ch==='ALL'||x[1]===ch));let weak=new Set(stats().filter(x=>x.acc<80).map(x=>x.topic));if(mode==='weak')pool=pool.filter(x=>weak.has(x[2]));if(mode!=='adaptive'&&mode!=='weak')pool=pool.filter(x=>x[3]===mode)||pool;if(!pool.length)pool=Q.filter(x=>x[0]===bid);pool=[...pool].sort(()=>Math.random()-.5);current=pool.slice(0,n);idx=0;score=0;$('#setup').classList.add('hidden');showQ()}
function showQ(){let x=current[idx];let opts=[...x[6]].sort(()=>Math.random()-.5);$('#quiz').innerHTML=`<div class="card q"><div class=meta>Q ${idx+1}/${current.length} • ${x[1]} • ${x[2]} • ${x[3]}</div><div class=question>${x[4]}</div><div class=options>${opts.map(o=>`<button class=option onclick="answer(this,${JSON.stringify(o)},${JSON.stringify(x[5])},${JSON.stringify(x)})">${o}</button>`).join('')}</div></div>`}
function answer(btn,choice,correct,x){$$('.option').forEach(b=>b.disabled=true);let ok=choice===correct;if(ok){score++;btn.classList.add('correct')}else{btn.classList.add('wrong');$$('.option').forEach(b=>{if(b.textContent===correct)b.classList.add('correct')})}state.history.push({topic:x[2],ok});state.seen.push(x[4]);save();setTimeout(()=>{idx++;idx<current.length?showQ():finish()},600)}
function finish(){let p=Math.round(score/current.length*100);$('#quiz').innerHTML='';$('#result').innerHTML=`<div class=card><h2>${score}/${current.length} — ${p}%</h2><p>${p>=85?'Strong run.':'Good diagnostic. The engine now knows more about your weak areas.'}</p><button class=primary onclick="show('weak')">See weak topics →</button></div>`;$('#setup').classList.remove('hidden');init()}
function renderWeak(){let s=stats();$('#weakTopics').innerHTML=s.length?s.map(x=>`<div class=row><span>${x.topic}<div class=bar><i style="width:${x.acc}%"></i></div></span><b>${x.acc}%</b></div>`).join(''):'<p>No data yet.</p>'}
function renderProgress(){renderWeak();$('#progressView').innerHTML=stats().map(x=>`<div class=row><span>${x.topic}</span><b>${x.n} attempts</b></div>`).join('')||'<p>No history yet.</p>'}
function renderBooks(){$('#books').innerHTML=BOOKS.map(b=>`<div class=row><span><b>${b.name}</b><br><small>${b.chapters.length} chapter slots</small></span></div>`).join('')}
init();
